[server]
host = "127.0.0.1"
port = 8090
tls_enabled = false

[logging]
level = "info"

[queue]
type = "disabled"

[service.audio]
host = "127.0.0.1"
port = 8081
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.asr]
host = "127.0.0.1"
port = 8080
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.alignment]
host = "127.0.0.1"
port = 8082
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.pipeline]
selected = "default"

[service.pipeline.definitions.default]
pre = ["audio_transform"]
transcription = "asr_transcribe"
post = ["alignment_enrich"]
