[server]
host = "0.0.0.0"
port = 8080
tls_enabled = false

[logging]
level = "info"

[queue]
type = "disabled"

[service.audio]
host = "audio-service"
port = 8080
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.asr]
host = "asr-service"
port = 8080
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.alignment]
host = "alignment-service"
port = 8080
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.pipeline]
selected = "production"

[service.pipeline.definitions.production]
pre = ["audio_transform"]
transcription = "asr_transcribe"
post = ["alignment_enrich"]
