[server]
host = "127.0.0.1"
port = 19080
tls_enabled = false

[logging]
level = "warn"

[queue]
type = "disabled"

[service.audio]
host = "127.0.0.1"
port = 18081
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.asr]
host = "127.0.0.1"
port = 18080
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.alignment]
host = "127.0.0.1"
port = 18082
tls_enabled = false
connect_timeout_ms = 3000
request_timeout_ms = 60000
max_decoding_message_bytes = 67108864
max_encoding_message_bytes = 67108864

[service.pipeline]
selected = "test"

[service.pipeline.definitions.test]
pre = ["audio_transform"]
transcription = "asr_transcribe"
post = ["alignment_enrich"]
