[server]
host = "127.0.0.1"
port = 8082
tls_enabled = false

[logging]
level = "debug"


[queue]
type = "disabled"

[service.audio]
sample_rate_hz = 16000
chunk_ms = 500

[service.asr]
model_path = "../models/ggml-large-v3-q5_0.bin"
default_language = "auto"
supported_languages = ["fr", "en"]
temperature = 0.0
threads = 6
dtw_preset = "base"
dtw_mem_size = 128
